### ISSUE TITLE
dependencies:   - { role: ansible-drush }

### ISSUE THREAD

**Issue by klemenkobetic** [thecarlhall/ansible-drupal#1]
which role is 

dependencies:
  - { role: ansible-drush }

?

**Comment by thecarlhall** [comment]
You can find that dependency here: https://galaxy.ansible.com/list#/roles/236

**Comment by thecarlhall** [comment]
also here: https://github.com/thecarlhall/ansible-drush

**Comment by klemenkobetic** [comment]
yes, but it would be best to rename it also in the meta file, wouldnt it?
