### ISSUE TITLE
debian.yml

### ISSUE THREAD

**Issue by klemenkobetic** [thecarlhall/ansible-drupal#2]
also, 
/etc/ansible/roles/thecarlhall.drupal/vars/debian.yml

should be

/etc/ansible/roles/thecarlhall.drupal/vars/Debian.yml

**Comment by thecarlhall** [comment]
Did you encounter errors?  I've been able to run this on my debian systems without error.

**Comment by klemenkobetic** [comment]
ubuntu14, yes, had to rename it
